name: workflow principal de cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v3

      
name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

      
name: Build
      run: ./gradlew build
      shell: bash

      
name: Test
      run: ./gradlew test
      shell: bash